### ISSUE TITLE
Can't create tenant with automatic installation (idoit-install) of the 'open' variant

### ISSUE THREAD

**Issue by affc** [i-doit/scripts#29]
### Expected behavior
Tenant creation successful.

### Actual behavior
Tenant creation fails because the file 'isys_module_import_csv.class.php' is not found. As a workaround, this file can be copied from the PRO zip file to the relevant directory (${INSTALL_DIR}/src/classes/modules/import_csv/).

### Steps to reproduce the behavior
Run idoit-install (from https://github.com/i-doit/scripts)

### Environment

| Question                  | Answer                            |
| ------------------------- | --------------------------------- |
| i-doit version            | 1.23                             |
| i-doit edition            | open                   |
| Operating system (OS)     | Debian |
| OS version                | 11.7.0 "bullseye"                       |

### Server logs
```
--------------------------------------------------------------------------------
$ sudo ./idoit-install
[...]
Do you want to create the initial i-doit tenant automatically? [Y]es [n]o: y
Install i-doit via console.php
Please enter a tenant name [leave empty for 'Your company name']: 
PHP Fatal error:  Uncaught Error: Class 'isys_module_import_csv' not found in /var/www/html/src/idoit/Console/IdoitConsoleApplication.php:131
Stack trace:
#0 /var/www/html/src/idoit/Console/IdoitConsoleApplication.php(27): idoit\Console\IdoitConsoleApplication->loadCommands()
#1 /var/www/html/console.php(22): idoit\Console\IdoitConsoleApplication->__construct()
#2 {main}
  thrown in /var/www/html/src/idoit/Console/IdoitConsoleApplication.php on line 131
Creating tenant failed
Operation failed. Please check what is wrong and try again.

```

**Comment by MichaelOv** [comment]
Hey @affc,

it seems that this was related to i-doit itself.

Actually, with i-doit 25, it is working.

```shell
Do you want to create the initial i-doit tenant automatically? [Y]es [n]o: 
Install i-doit via console.php
Please enter a tenant name [leave empty for 'Your company name']: 
 ----------------------------------------------------------------------------- -------- 
  Message                                                                       Result  
 ----------------------------------------------------------------------------- -------- 
  Create Tenant                                                                 OK      
  DB                                                                            OK      
  Create DB                                                                     OK      
  Import DB: idoit_data                                                         OK      
  Check tenant exist with Your company name and DB idoit_data: does not exist   FAIL    
  Add tenant Your company name: added with id 1                                 OK      
  Adding persons                                                                OK      
  Inserting persons to database: : Users was successfully added:                OK      
 ----------------------------------------------------------------------------- -------- 

Tenant 'Your company name' created
```
